config/routes.rb
Rails.application.routes.draw do
  resources :nodes, :only => [] do
    post 'add_to_cache', :on => :member
  end

  resources :cached_nodes, :except => [:show, :index]

  get 'reset' => 'application#reset'
  get 'apply' => 'application#apply'

  root to: 'application#index'
end

app/models/cached_node.rb
class CachedNode < RedisRecord::Base
  record_columns primary_key: 'uuid',
                 fields: [:id, :value, :ancestry, :deleted_at, :created_at]

  # smart ancestry for redis record
  include SmartAncestry
  has_smart_ancestry

  def deleted?
    self.deleted_at.present?
  end

  def mark_descendants_deleted
    self.children.each do |r|
      r.deleted_at = Time.zone.now
      r.save
      r.mark_descendants_deleted if r.children.any?
    end
  end

  def self.with_id
    all.select { |r| r.id.present? }.sort do |a,b|
      a.ancestry_depth <=> b.ancestry_depth
    end
  end

  def self.without_id
    all.select { |r| r.id.blank? }.sort do |a,b|
      comp = a.ancestry_depth <=> b.ancestry_depth
      comp = a.id.presence.to_i <=> b.id.presence.to_i if comp.zero?
      comp = a.created_at <=> b.created_at if comp.zero?
      comp
    end
  end
end

app/models/node.rb
class Node < ActiveRecord::Base
  has_ancestry :cache_depth => true

  after_save :mark_descendants_deleted, if: -> { self.deleted_at.present? }

  scope :deleted,     -> { where.not(deleted_at: nil) }
  scope :not_deleted, -> { where(deleted_at: nil) }

  def for_cache
    self.as_json(only: [:id, :value, :ancestry_depth, :deleted_at]).merge(:ancestry => parent_id)
  end

  def deleted?
    self.deleted_at.present?
  end

  private

  def mark_descendants_deleted
    descendants.update_all(deleted_at: Time.zone.now)
  end
end

app/controllers/application_controller.rb
require 'rake'
TreeNodes::Application.load_tasks
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  after_filter :flash_to_headers

  def index
    @roots = Node.at_depth(0).order(:id)
    @cached_nodes = TreeForRender.new.build_tree
  end

  def apply
    ChangesApplier.apply
    flash[:notice] = 'All changes were saved to database'
    redirect_to root_path
  end

  def reset
    Rake::Task['db:schema:load'].reenable
    Rake::Task['db:schema:load'].invoke
    Rake::Task['db:seed'].reenable
    Rake::Task['db:seed'].invoke
    CachedNode.destroy_all
    flash[:notice] = 'All data were reseted to initial state'
    redirect_to root_path
  end

  private

  def flash_to_headers
    return unless request.xhr?
    if (message = flash_message)
      response.headers['X-Message'] = message
      response.headers["X-Message-Type"] = flash_type.to_s

      flash.discard
    end
  end

  def flash_message
    [:error, :warning, :notice].each do |type|
      return flash[type] unless flash[type].blank?
    end

    nil
  end

  def flash_type
    [:error, :warning, :notice].each do |type|
      return type unless flash[type].blank?
    end

    nil
  end
end

app/controllers/cached_nodes_controller.rb
class CachedNodesController < ApplicationController
  respond_to :js

  before_filter :check_value, only: [:create, :update]

  def edit
    @cached_node = CachedNode.find(params[:id])
    render :edit, layout: false
  end

  def update
    @cached_node = CachedNode.find(params[:id])
    @cached_node.value = params[:value]
    make_flash('Node not saved') unless @cached_node.save
    render_list
  end

  def new
    if params[:parent_id].present? || CachedNode.can_add_root?
      @cached_node = CachedNode.new
      render :new, layout: false
    else
      return head(:forbidden)
    end
  end

  def create
    @cached_node = CachedNode.new
    @cached_node.value = params[:value]

    parent = CachedNode.find(params[:parent_id])
    @cached_node.parent = parent

    make_flash('Node not created') unless @cached_node.save
    render_list
  end

  def destroy
    @cached_node = CachedNode.find(params[:id])
    @cached_node.deleted_at = Time.zone.now.to_s
    if @cached_node.save
      @cached_node.mark_descendants_deleted
    else
      make_flash('Can`t delete node')
    end
    render_list
  end

  private

  def check_value
    unless params[:value].present?
      make_flash('Value cant be blank')
      flash_to_headers
      render_list
    end
  end

  def make_flash(message)
    flash[:notice] = message
  end

  def render_list
    @cached_nodes = TreeForRender.new.build_tree
    render partial: 'cached_nodes/list', locals: { cached_nodes: @cached_nodes }
  end
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
  respond_to :js

  def add_to_cache
    id = params[:id]

    if CachedNode.find_by(:id, id).present?
      flash[:notice] = "Node is already added"
      render nothing: true
    else
      @node = Node.find(params[:id])
      @cached_node = CachedNode.new(@node.for_cache)
      if @cached_node.save
        @cached_nodes = TreeForRender.new.build_tree
      else
        flash[:notice] = "Node is not saved"
        render nothing: true
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/index.html.erb
<div class="container">
  <div class="nodes">
    <div class="tree_view">
      <ul class="ancestry">
        <%= render @roots %>
      </ul>
    </div>
  </div>

  <%= link_to ">>>", '#', :class => 'button export' %>

  <div class="cached_nodes">
    <div class="tree_view">
      <%= render partial: 'cached_nodes/list', locals: { cached_nodes: @cached_nodes} %>
    </div>
  </div>
</div>

<%= link_to "Add", '#', class: 'button new operate' %>
<%= link_to "Delete", '#', class: 'button delete operate' %>
<%= link_to "Edit", '#', class: 'button edit operate' %>
<%= link_to "Apply", apply_path, class: 'button apply' %>
<%= link_to "Reset", reset_path, class: 'button reset' %>

app/views/cached_nodes/_form.html.erb
<div class="popup_container">
  <%= form_tag path, method: method, class: 'ajaxed_form' do %>
    <%= text_field_tag :value, @cached_node.value %>
    <%= hidden_field_tag :parent_id, params[:parent_id] %>
    <%= submit_tag 'Save', class: 'apply' %>
    <%= link_to "Cancel", '#', class: :cancel %>
  <% end %>
</div>

app/views/cached_nodes/_list.html.erb
<ul class='ancestry'>
  <% cached_nodes.each do |id, node_hash| %>
    <li>
      <% node = node_hash[:obj] %>
      <% children = node_hash[:children] %>
      <span id=<%= node.uuid %> class=<%= node.deleted? ? 'deleted' : '' %>>
        <%= node.value %>
      </span>
      <% if children.any? %>
        <%= render partial: 'cached_nodes/list', locals: { cached_nodes: children } %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/cached_nodes/edit.html.erb
<%= render partial: 'form', locals: { path: cached_node_path(@cached_node.uuid), method: :patch } %>

app/views/cached_nodes/new.html.erb
<%= render partial: 'form', locals: { path: cached_nodes_path, method: :post } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TreeNodes</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="flash-message">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, id: "flash_#{name}" %>
    <% end %>
  </div>

<%= yield %>

</body>
</html>

app/views/nodes/_node.html.erb
<li class="child">
  <span id=<%= node.id %> class=<%= node.deleted? ? 'deleted' : '' %>>
    <%= node.value %>
  </span>
  <ul class="ancestry">
    <%= render node.children.order(:id) %>
  </ul>
</li>

app/views/nodes/add_to_cache.js.erb
$('.cached_nodes .tree_view').html(
  "<%= j(render partial: 'cached_nodes/list', locals: { cached_nodes: @cached_nodes }) %>"
)